Update to v24 upstream, minor build edits, add Full RBF config option
Start9Labs/bitcoind-wrapper pull request #107
Opened 2022-12-02 18:50 UTC by kn0wmad

2022-12-02 23:50 UTC, chrisguida requested changes
Just some questions and minor nits

2022-12-02 23:50 UTC, chrisguida commented on Dockerfile
> +# RUN patch -u SHA256SUMS.asc -i SHA256SUMS.asc.patch
If we don't need the patch file, let's delete the patch file. Also just delete this line, don't comment.

2022-12-02 23:50 UTC, chrisguida commented on Dockerfile
> +# RUN sed -i '/AC_PREREQ/a\AR_FLAGS=cr' src/univalue/configure.ac
why was this added originally?

also delete if not needed

2022-12-02 23:50 UTC, chrisguida commented on Dockerfile
> +# RUN sed -i s:sys/fcntl.h:fcntl.h: src/compat.h
same as above, why was this originally here?

2022-12-02 23:50 UTC, chrisguida commented on manifest.yaml
> +    * Use new eOS 0.3.3 APIs
This line not needed, unless there's some js conversion i missed

2022-12-02 23:50 UTC, chrisguida commented on migrations/gt_22_0_0_lt_23_0_0.sh
>  fi
Make it a blank line, as is customary for all checked-in files

```suggestion
fi

```

2022-12-02 23:50 UTC, chrisguida commented on scripts/services/getConfig.ts
> +            "default": 128,
Have we determined that 128 is better than 64?

2022-12-02 23:50 UTC, chrisguida commented on scripts/services/getConfig.ts
> +              "Policy for your node to use for relaying and mining unconfirmed transactions.  For details, see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-24.0.md",
Link to the actual section where it mentions full rbf?

```suggestion
              "Policy for your node to use for relaying and mining unconfirmed transactions.  For details, see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-24.0.md#notice-of-new-option-for-transaction-replacement-policies",
```

2022-12-04 23:54 UTC, kn0wmad commented on Dockerfile
> +# RUN sed -i '/AC_PREREQ/a\AR_FLAGS=cr' src/univalue/configure.ac
I did not create this dockerfile, we'd have to ask @dr-bonez most likely

2022-12-04 23:54 UTC, kn0wmad commented on Dockerfile
> +# RUN sed -i s:sys/fcntl.h:fcntl.h: src/compat.h
Same as above

2022-12-04 23:58 UTC, kn0wmad commented on Dockerfile
> +# RUN patch -u SHA256SUMS.asc -i SHA256SUMS.asc.patch
I left all this stuff for the review, removing

2022-12-05 00:01 UTC, kn0wmad commented on scripts/services/getConfig.ts
> +            "default": 128,
This preference was given by @MattDHill and @BitcoinMechanic - I'm not sure how deep the testing went on it.  I'm not convinced it solves anything, but it also probably won't hurt anything

2022-12-05 16:11 UTC, chrisguida commented on Dockerfile
> +# RUN patch -u SHA256SUMS.asc -i SHA256SUMS.asc.patch
The review will show all changes, no need to do this in the future :)

2022-12-05 16:12 UTC, chrisguida commented on Dockerfile
> +# RUN sed -i '/AC_PREREQ/a\AR_FLAGS=cr' src/univalue/configure.ac
In that case, what does it fix?

2022-12-05 16:12 UTC, chrisguida commented on Dockerfile
> +# RUN sed -i s:sys/fcntl.h:fcntl.h: src/compat.h
In that case, what does it fix?

2022-12-05 18:16 UTC, kn0wmad commented on Dockerfile
> +# RUN sed -i '/AC_PREREQ/a\AR_FLAGS=cr' src/univalue/configure.ac
As I said, the build fails with these 2 lines included

2022-12-05 18:22 UTC, chrisguida commented on Dockerfile
> +# RUN sed -i '/AC_PREREQ/a\AR_FLAGS=cr' src/univalue/configure.ac
Yes, I'm looking for something more specific than "the build fails". What fails? What's the error message you're seeing?

2022-12-05 18:55 UTC, kn0wmad commented on Dockerfile
> +# RUN patch -u SHA256SUMS.asc -i SHA256SUMS.asc.patch
This is such that I can immediately replace the line if necessary

2022-12-05 19:35 UTC, chrisguida commented on Dockerfile
> +# RUN sed -i '/AC_PREREQ/a\AR_FLAGS=cr' src/univalue/configure.ac
Yeah maybe we should check with @dr-bonez , the file not existing does not mean that it's ok to delete this change. Perhaps the file was simply moved upstream

2022-12-06 23:42 UTC, chrisguida approved these changes
Looks good

2022-12-07 00:11 UTC, merged