Re add peers.dat action
Start9Labs/bitcoind-wrapper pull request #122
Opened 2023-07-06 02:32 UTC by Dominion5254

2023-07-06 14:28 UTC, kn0wmad requested changes
Has this been tested?

2023-07-06 14:28 UTC, kn0wmad commented on scripts/dependencies.ts
> +export { exists } from "https://deno.land/x/embassyd_sdk@v0.3.1.0.3/mod.ts";
I don't think it's necessary to use an old version of the SDK here - I was exporting everything from latest

2023-07-06 19:24 UTC, Dominion5254 commented
Yes, I tested twice with no issues. Release is on Alpha and more testing would be appreciated.

2023-07-10 19:56 UTC, kn0wmad approved these changes

2023-07-11 16:43 UTC, merged