Update 23
Start9Labs/bitcoind-wrapper pull request #72
Opened 2022-06-10 15:36 UTC by kn0wmad

Updated Bitcoin, added Bisq support, migrations updated for v23

2022-06-13 15:25 UTC, chrisguida requested changes
See comments

2022-06-13 22:41 UTC, chrisguida commented on migrations/lt_22_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
this is a bit aggressive, are we ok with just forcing everyone to turn these up? @ProofOfKeags @dr-bonez

2022-06-13 22:42 UTC, chrisguida commented on migrations/lt_22_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
also this looks like it's in the wrong migration, this is going back *to* v0.21 (or below)

2022-06-13 22:43 UTC, chrisguida commented on migrations/lt_23_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
same as above, this should be in the `from` migration, no?

2022-06-14 00:00 UTC, kn0wmad commented on migrations/lt_22_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
This is a naive way of setting the newly decreed "sensible default" on any move, keeping in mind these are the max for this version.  Direction is correct I think

2022-06-14 00:16 UTC, kn0wmad commented on migrations/lt_23_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
This is backwards from how I understand it and how testing seemed to verify - are you sure?

2022-06-14 05:22 UTC, kn0wmad commented on migrations/lt_22_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
This sets to 4/32 RPC resources because it is accounting for coming from a higher version, where higher resources are permitted.  The only better way would be to set to where the user has them OR 4/32, whichever is lower.  Not sure how often this would ever happen, and 4/32 are sensible defaults for this version

2022-06-14 05:23 UTC, kn0wmad commented on migrations/lt_23_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
I think this is correct, when going TO <23, you will need to remove bloom filters as they are not an available feature, when coming FROM <23, you will need to set filters to false as they cannot be null

2022-06-14 15:16 UTC, chrisguida commented on migrations/lt_22_0_0.sh
> +    yq -i '.rpc.advanced.workqueue |= 32' /root/.bitcoin/start9/config.yaml
the "to" migration will never run when coming from a higher version. Instead, the higher version's "to" migration will run.

2022-06-15 16:09 UTC, chrisguida commented on migrations/lt_22_0_0.sh
> +    yq -i 'del(.advanced.bloomfilters)' /root/.bitcoin/start9/config.yaml
Did you try putting this on the same line as the blockfilters key deletion? Curious if that works

2022-06-15 16:09 UTC, chrisguida commented on migrations/lt_22_0_0.sh
> +    yq -i 'del(.advanced.bloomfilters)' /root/.bitcoin/start9/config.yaml
Did you try putting this on the same line as the blockfilters key deletion? Curious if that works

2022-06-15 16:11 UTC, chrisguida commented on migrations/eq_22_0_0.sh
>  elif [ $1 = "to" ]; then
hopefully no one is downgrading to 22.0.0, that version was broken. but this is fine.

2022-06-15 16:11 UTC, chrisguida approved these changes
This looks fine, let's merge

2022-06-15 16:30 UTC, merged