Update manifest.yaml
Start9Labs/bitcoind-wrapper pull request #91
Opened 2022-08-17 17:43 UTC by kn0wmad

2022-08-17 19:33 UTC, chrisguida commented on manifest.yaml
> +    description: "Rebuilds the block and chainstate databases starting from genesis. If blocks already exist on disk, these are used rather than being redownloaded. This usually means downloading the
This actually isn't true for archival nodes

2022-08-17 19:35 UTC, chrisguida requested changes
see comment

2022-08-17 20:07 UTC, kn0wmad commented on manifest.yaml
> +    description: "Rebuilds the block and chainstate databases starting from genesis. If blocks already exist on disk, these are used rather than being redownloaded. This usually means downloading the
What is it that is happening when an archival is reindexed?  It seems to take as long as a full IBD

2022-08-17 20:09 UTC, chrisguida commented on manifest.yaml
> +    description: "Rebuilds the block and chainstate databases starting from genesis. If blocks already exist on disk, these are used rather than being redownloaded. This usually means downloading the
It's re-validating all blocks from disk, and reinserting them into the index.

2022-08-17 20:10 UTC, chrisguida commented on manifest.yaml
> +    description: "Rebuilds the block and chainstate databases starting from genesis. If blocks already exist on disk, these are used rather than being redownloaded. This usually means downloading the
Basically, everything IBD does _except_ redownload the blocks

2022-08-17 20:32 UTC, kn0wmad commented
Okay, so what is the final copy change here then?  I feel like I should just assign to you as you probably could have written it in 20 seconds @chrisguida

2022-08-17 21:16 UTC, chrisguida commented
@kn0wmad see my code suggestion for what I think it should be. This is your issue, so you can decide whether it closes your issue

2022-08-18 17:41 UTC, chrisguida commented
Closes #90

2022-08-18 17:41 UTC, merged