remove n_proc
Start9Labs/bitcoind-wrapper pull request #95
Opened 2022-09-07 17:21 UTC by BitcoinMechanic

2022-09-07 22:35 UTC, dr-bonez requested changes
Remove `${N_PROC}` in `make -j${N_PROC}` on line 129

2022-09-07 22:43 UTC, dr-bonez approved these changes

2022-09-07 22:43 UTC, merged

2022-09-07 22:58 UTC, chrisguida commented on Dockerfile
> +RUN make -j
does `-j` work like this? just... with no core count specifier?

2022-09-07 23:01 UTC, BitcoinMechanic commented on Dockerfile
> +RUN make -j
yes

2022-09-08 13:48 UTC, chrisguida commented on Dockerfile
> +RUN make -j
why not just remove `-j` entirely?